export const TYPO = {
  D1: {
    fontFamily: 'Tenada',
    fontStyle: 'normal',
    fontWeight: 800,
    fontSize: '2.625rem',
    lineHeight: '3.25rem',
  },
  D2: {
    fontFamily: 'Pretendard-Bold',
    fontStyle: 'normal',
    fontWeight: 700,
    fontSize: '1.625rem',
    lineHeight: '2.125rem',
  },
  H1: {
    fontFamily: 'Pretendard-Bold',
    fontStyle: 'normal',
    fontWeight: 700,
    fontSize: '1.375rem',
    lineHeight: '2rem',
  },
  H2: {
    fontFamily: 'Pretendard-Bold',
    fontStyle: 'normal',
    fontWeight: 700,
    fontSize: '1.25rem',
    lineHeight: '1.875rem',
  },
  T1: {
    fontFamily: 'Pretendard-Bold',
    fontStyle: 'normal',
    fontWeight: 700,
    fontSize: '1.1875rem',
    lineHeight: '1.75rem',
  },
  T2: {
    fontFamily: 'Pretendard-Semibold',
    fontStyle: 'normal',
    fontWeight: 600,
    fontSize: '1.25rem',
    lineHeight: '1.875rem',
  },
  T3: {
    fontFamily: 'Pretendard-Medium',
    fontStyle: 'normal',
    fontWeight: 600,
    fontSize: '1.25rem',
    lineHeight: '1.875rem',
  },
  B1: {
    fontFamily: 'Pretendard-Regular',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: '1.0625rem',
    lineHeight: '1.5625rem',
  },
  B2: {
    fontFamily: 'Pretendard-Bold',
    fontStyle: 'normal',
    fontWeight: 700,
    fontSize: '0.9375rem',
    lineHeight: '1.4375rem',
  },
  B3: {
    fontFamily: 'Pretendard-SemiBold',
    fontStyle: 'normal',
    fontWeight: 600,
    fontSize: '0.9375rem',
    lineHeight: '1.4375rem',
  },
  B4: {
    fontFamily: 'Pretendard-Medium',
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: '0.9375rem',
    lineHeight: '1.4375rem',
  },
  B5: {
    fontFamily: 'Pretendard-Medium',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: '0.875rem',
    lineHeight: '1.25rem',
  },
  B6: {
    fontFamily: 'Pretendard-Medium',
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: '0.8125rem',
    lineHeight: '1.25rem',
  },
  B7: {
    fontFamily: 'Pretendard-Bold',
    fontStyle: 'normal',
    fontWeight: 700,
    fontSize: '0.8125rem',
    lineHeight: '1.25rem',
  },
};
